module parkind1

implicit none

INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13,300)
! INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(6,37) ! single precision

end module parkind1
